language: swift
os: osx
osx_image: xcode11.6
git:
  depth: 1
  
jobs:
  include:
   - stage: "Build & Test"
   - script: xcodebuild -workspace Covid-19.xcodeproj -scheme Covid-19Test -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone 11 Pro Max,OS=13.6"
      name: "Build Example Project"
